---
abstract: 'POSIX Real-time signal handling functions'
author:
  - 'Leon Timmermans <fawaka@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::Exception: 0
  Test::More: 0.88
  Time::HiRes: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POSIX-RT-Signal
requires:
  Carp: 0
  Devel::CheckLib: 0
  POSIX: 0
  Sub::Exporter: 0
  XSLoader: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=POSIX-RT-Signal
  repository: git://github.com/Leont/posix-rt-signal.git
version: 0.007
